"""Initial migration.

Revision ID: 93a9f8b8928e
Revises:
Create Date: 2022-05-27 02:41:37.984875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93a9f8b8928e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("users", "user_name", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(length=256), nullable=False)
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["user_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "password", existing_type=sa.VARCHAR(length=256), nullable=True)
    op.alter_column("users", "user_name", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True)
    # ### end Alembic commands ###
